---
build:
  image: golang
  commands:
    - free

publish:
  docker:
    username: naga
    password: $$DOCKER_PASSWORD 
    email: naga@igraviton.com
    registry: registry.f3rn.com
    repo: test
#    file: Dockerfile
    insecure: false

