---
cache:
    mount:
        - node_modules
        - .git
 
build:
  image: node:5.11.1
  commands:
    - npm install
    - npm test

publish:
  docker:
    username: naga
    password: $$DOCKER_PASSWORD 
    email: naga@igraviton.com
    registry: registry.f3rn.com
    repo: test
    file: Dockerfile
    insecure: false

